name: 'Create GCS Bucket If Not Exists'
description: 'Checks for a GCS bucket and creates it if it does not exist'
inputs:
  bucket_name:
    description: 'The name of the GCS bucket'
    required: true
  project_id:
    description: 'The GCP project ID'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_BUCKET_NAME: ${{ inputs.bucket_name }}
    INPUT_PROJECT_ID: ${{ inputs.project_id }}
    GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
	