---
- name: Sample Playbook
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Display a message
      debug:
        msg: "Hello from Ansible!"
    
    - name: Create a test file
      file:
        path: /tmp/ansible-test.txt
        state: touch
        mode: '0644' 