---
- name: Test Ansible GitOps Service with Multiple Tasks
  hosts: localhost
  gather_facts: true
  vars:
    test_dir: /tmp/ansible-gitops-test
    test_files:
      - name: system_info.txt
        content: "System: {{ ansible_hostname }}\nOS: {{ ansible_distribution }} {{ ansible_distribution_version }}\nKernel: {{ ansible_kernel }}"
      - name: git_info.txt
        content: "Last Git Commit: {{ lookup('pipe', 'git rev-parse HEAD') }}\nBranch: {{ lookup('pipe', 'git rev-parse --abbrev-ref HEAD') }}"
      - name: timestamp.txt
        content: "Last Run: {{ ansible_date_time.iso8601 }}"

  tasks:
    - name: Create test directory structure
      file:
        path: "{{ test_dir }}/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - logs
        - data
        - config

    - name: Create test files with information
      copy:
        content: "{{ item.content }}"
        dest: "{{ test_dir }}/{{ item.name }}"
        mode: '0644'
      loop: "{{ test_files }}"

    - name: Get system resource information
      shell: |
        echo "CPU Info:" > {{ test_dir }}/system_resources.txt
        lscpu | grep "Model name" >> {{ test_dir }}/system_resources.txt
        echo -e "\nMemory Info:" >> {{ test_dir }}/system_resources.txt
        free -h >> {{ test_dir }}/system_resources.txt
        echo -e "\nDisk Usage:" >> {{ test_dir }}/system_resources.txt
        df -h / >> {{ test_dir }}/system_resources.txt
      register: resource_info
      changed_when: false

    - name: Create a test configuration file
      template:
        src: test-config.j2
        dest: "{{ test_dir }}/config/test.conf"
        mode: '0644'

    - name: Generate a test log entry
      copy:
        content: |
          [{{ ansible_date_time.iso8601 }}] INFO: Test playbook execution started
          [{{ ansible_date_time.iso8601 }}] INFO: Host: {{ ansible_hostname }}
          [{{ ansible_date_time.iso8601 }}] INFO: User: {{ ansible_user_id }}
          [{{ ansible_date_time.iso8601 }}] INFO: Git Branch: {{ lookup('pipe', 'git rev-parse --abbrev-ref HEAD') }}
        dest: "{{ test_dir }}/logs/test.log"
        mode: '0644'

    - name: Display all created files
      find:
        paths: "{{ test_dir }}"
        patterns: "*"
      register: created_files

    - name: Show created files
      debug:
        msg: "Created file: {{ item.path }}"
      loop: "{{ created_files.files }}"

    - name: Show system information
      debug:
        msg: "Running on {{ ansible_hostname }} with OS {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Show Git information
      debug:
        msg: "Git commit: {{ lookup('pipe', 'git rev-parse HEAD') }}" 