name: Test Ansible Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Ansible Playbook
        uses: ./
        with:
          playbook_path: playbook.yml
          inventory_path: inventory.yml
          extra_vars: '{"test_var": "value"}' 